### ISSUE TITLE
floating point math bug

### ISSUE THREAD

**Issue by Alxytho** [averwhy/fishypy-discord-game#12]
experience gained from fishing is 10x experience earned
0.001 XP gained -> 0.01 XP earned

**Comment by averwhy** [comment]
I *think* i know whats causing this. I'll aim to fix this in v1.0.2

**Comment by averwhy** [comment]
ok, turns out when displaying caught xp it divided the rarity by 100 (correct value) **BUT** when updating the users xp, it divided by only *10*. When updating XP it divides by 100 now. 
Thanks for catching this, i would've never noticed this otherwise
Are you on the support server? You've earned the contributor role
